
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.enchanted]
			alder = true
			hawthorn = true
			rowan = true

		[types.wood_type.biomesoplenty]
			fir = true
			pine = true
			maple = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.vampirism]
			dark_spruce = true
			cursed_spruce = true

		[types.wood_type.werewolves]
			jacaranda = true
			magic = true

	[types.stone_type]

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.naturalist]
			shellstone = true

		[types.stone_type.biomesoplenty]
			brimstone = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.vampirism]
			dark_stone = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			rainbow_birch = true
			snowblossom = true
			null = true
			cypress = true
			fir = true
			pine = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.enchanted]
			alder = true
			hawthorn = true
			rowan = true

		[types.leaves_type.vampirism]
			dark_spruce = true

		[types.leaves_type.werewolves]
			jacaranda = true
			magic = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.create]
			window_pane = true
			window = true

